"""Add photo_url to Master

Revision ID: 97ecc6cf23e9
Revises: c2d3043f1571
Create Date: 2025-02-26 13:11:36.044855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97ecc6cf23e9'
down_revision = 'c2d3043f1571'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('masters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_url', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('masters', schema=None) as batch_op:
        batch_op.drop_column('photo_url')

    # ### end Alembic commands ###
