"""Веб часть начало

Revision ID: c2d3043f1571
Revises: b5eda678baf5
Create Date: 2025-02-26 01:42:39.630099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2d3043f1571'
down_revision = 'b5eda678baf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.alter_column('reminder_sent',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('avatar_url')

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.alter_column('reminder_sent',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###
